server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FUCarRentingSystem;encrypt=false;trustServerCertificate=true
    username: sa
    password: Password123! # update this accordingly
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
